const courseData = [
  {
    id: 1,
    title: "Best Practices in Multishift Operations",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2024,
    certificate: "PMI",
    duration: "5 Days",
    date: "2024-01-08",
    price: 5000,
  },
  {
    id: 2,
    title: "Leadership in Complex Environments",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2024,
    certificate: "CPD",
    duration: "10 Days",
    date: "2024-02-12",
    price: 7500,
  },
  {
    id: 3,
    title: "Project Management Essentials",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2025,
    certificate: "PMI",
    duration: "10 Days",
    date: "2025-02-15",
    price: 6000,
  },
  {
    id: 4,
    title: "Risk Assessment Strategies",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2024,
    certificate: "CPD",
    duration: "5 Days",
    date: "2024-01-05",
    price: 4000,
  },
  {
    id: 5,
    title: "Advanced Project Management",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2024,
    certificate: "PMI",
    duration: "10 Days",
    date: "2024-01-10",
    price: 8500,
  },
  {
    id: 6,
    title: "Agile Methodologies",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2025,
    certificate: "CPD",
    duration: "5 Days",
    date: "2025-02-20",
    price: 4500,
  },
  {
    id: 7,
    title: "Supply Chain Optimization",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2024,
    certificate: "PMI",
    duration: "10 Days",
    date: "2024-01-25",
    price: 9000,
  },
  {
    id: 8,
    title: "Digital Transformation Leadership",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2024,
    certificate: "CPD",
    duration: "5 Days",
    date: "2024-02-05",
    price: 6500,
  },
  {
    id: 9,
    title: "Data-Driven Decision Making",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2025,
    certificate: "PMI",
    duration: "5 Days",
    date: "2025-01-08",
    price: 7000,
  },
  {
    id: 10,
    title: "Finance for Non-Financial Managers",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2025,
    certificate: "CPD",
    duration: "10 Days",
    date: "2025-02-15",
    price: 5000,
  },
  {
    id: 11,
    title: "Leading with Emotional Intelligence",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2024,
    certificate: "PMI",
    duration: "5 Days",
    date: "2024-01-10",
    price: 5200,
  },
  {
    id: 12,
    title: "Customer Experience Management",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2024,
    certificate: "CPD",
    duration: "10 Days",
    date: "2024-02-18",
    price: 6200,
  },
  {
    id: 13,
    title: "Strategic Negotiation Skills",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2025,
    certificate: "PMI",
    duration: "10 Days",
    date: "2025-02-25",
    price: 5800,
  },
  {
    id: 14,
    title: "Effective Communication Techniques",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2024,
    certificate: "CPD",
    duration: "5 Days",
    date: "2024-01-15",
    price: 5400,
  },
  {
    id: 15,
    title: "Digital Marketing Strategies",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2024,
    certificate: "PMI",
    duration: "5 Days",
    date: "2024-02-01",
    price: 6800,
  },
  {
    id: 16,
    title: "Effective Team Leadership",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2025,
    certificate: "CPD",
    duration: "10 Days",
    date: "2025-01-22",
    price: 6000,
  },
  {
    id: 17,
    title: "Organizational Change Management",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2025,
    certificate: "PMI",
    duration: "5 Days",
    date: "2025-02-07",
    price: 7100,
  },
  {
    id: 18,
    title: "Leadership Coaching",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2024,
    certificate: "CPD",
    duration: "5 Days",
    date: "2024-01-18",
    price: 6300,
  },
  {
    id: 19,
    title: "Business Analytics and Data Science",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2024,
    certificate: "PMI",
    duration: "10 Days",
    date: "2024-02-12",
    price: 7500,
  },
  {
    id: 20,
    title: "Financial Risk Management",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2024,
    certificate: "CPD",
    duration: "10 Days",
    date: "2024-01-28",
    price: 5700,
  },
  {
    id: 21,
    title: "Innovation in Product Management",
    format: "Classroom",
    venue: "Amsterdam",
    month: "January",
    year: 2024,
    certificate: "PMI",
    duration: "10 Days",
    date: "2024-01-12",
    price: 8400,
  },
  {
    id: 22,
    title: "Supply Chain Resilience",
    format: "Online",
    venue: "Barcelona",
    month: "February",
    year: 2025,
    certificate: "CPD",
    duration: "5 Days",
    date: "2025-02-10",
    price: 6000,
  },
  {
    id: 23,
    title: "Advanced Business Analytics",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2024,
    certificate: "PMI",
    duration: "10 Days",
    date: "2024-02-22",
    price: 7000,
  },
  {
    id: 24,
    title: "Strategic Brand Management",
    format: "Online",
    venue: "Barcelona",
    month: "January",
    year: 2025,
    certificate: "CPD",
    duration: "5 Days",
    date: "2025-01-25",
    price: 5600,
  },
  {
    id: 25,
    title: "Professional Ethics in Business",
    format: "Classroom",
    venue: "Amsterdam",
    month: "February",
    year: 2024,
    certificate: "PMI",
    duration: "5 Days",
    date: "2024-02-03",
    price: 5000,
  },
];

export default courseData;
